// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BKA.Tools.CrewFinding.BehaviourTest.CrewParties.Features.Queries
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ViewRecentlyCreatedCrewPartiesFeature : object, Xunit.IClassFixture<ViewRecentlyCreatedCrewPartiesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ViewRecentlyCreatedCrewParties.feature"
#line hidden
        
        public ViewRecentlyCreatedCrewPartiesFeature(ViewRecentlyCreatedCrewPartiesFeature.FixtureData fixtureData, BKA_Tools_CrewFinding_BehaviourTest_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CrewParties/Features/Queries", "View recently created Crew Parties", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Viewing Crew Parties created within the last hour")]
        [Xunit.TraitAttribute("FeatureTitle", "View recently created Crew Parties")]
        [Xunit.TraitAttribute("Description", "Viewing Crew Parties created within the last hour")]
        public void ViewingCrewPartiesCreatedWithinTheLastHour()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Viewing Crew Parties created within the last hour", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
        testRunner.Given("the current time is \"2023-07-29T15:00:00\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "CrewPartyName",
                            "CaptainHandle",
                            "CreationTime",
                            "MaxCrewSize",
                            "Languages",
                            "System",
                            "PlanetarySystem",
                            "PlanetMoon",
                            "Location",
                            "Description",
                            "Activity"});
                table4.AddRow(new string[] {
                            "The Stellar Hunters",
                            "Rowan",
                            "2023-07-29T14:20:00",
                            "4",
                            "ES, EN",
                            "Stanton",
                            "Crusader",
                            "Crusader",
                            "Seraphim Station",
                            "Elite bounty hunters",
                            "Bounty Hunting"});
                table4.AddRow(new string[] {
                            "The Galactic Voyagers",
                            "Ada",
                            "2023-07-29T14:45:00",
                            "5",
                            "EN, DE",
                            "Terra",
                            "Sol",
                            "Terra",
                            "New Austin",
                            "Space explorers",
                            "Exploration"});
                table4.AddRow(new string[] {
                            "The Lunar Marauders",
                            "Kai",
                            "2023-07-29T13:00:00",
                            "3",
                            "EN, FR",
                            "Hurston",
                            "Stanton",
                            "Ariel",
                            "Lorville",
                            "Lunar miners",
                            "Mining"});
                table4.AddRow(new string[] {
                            "The Space Pioneers",
                            "Eve",
                            "2023-07-29T13:30:00",
                            "6",
                            "ES, PT",
                            "Stanton",
                            "Crusader",
                            "Crusader",
                            "Port Olisar",
                            "Intergalactic pioneers",
                            "Trade"});
#line 5
        testRunner.And("the following Crew Parties exist:", ((string)(null)), table4, "And ");
#line hidden
#line 11
        testRunner.When("the player searches for Crew Parties created within the last hour", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "CrewPartyName",
                            "CaptainHandle",
                            "CreationTime",
                            "MaxCrewSize",
                            "Languages",
                            "System",
                            "PlanetarySystem",
                            "PlanetMoon",
                            "Location",
                            "Description",
                            "Activity"});
                table5.AddRow(new string[] {
                            "The Stellar Hunters",
                            "Rowan",
                            "2023-07-29T14:20:00",
                            "4",
                            "ES, EN",
                            "Stanton",
                            "Crusader",
                            "Crusader",
                            "Seraphim Station",
                            "Elite bounty hunters",
                            "Bounty Hunting"});
                table5.AddRow(new string[] {
                            "The Galactic Voyagers",
                            "Ada",
                            "2023-07-29T14:45:00",
                            "5",
                            "EN, DE",
                            "Terra",
                            "Sol",
                            "Terra",
                            "New Austin",
                            "Space explorers",
                            "Exploration"});
#line 12
        testRunner.Then("Allan should see the following Crew Parties:", ((string)(null)), table5, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ViewRecentlyCreatedCrewPartiesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ViewRecentlyCreatedCrewPartiesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
