// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BKA.Tools.CrewFinding.BehaviourTest.Crews.Features.Commands
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class DisbandAllExpiredCrewsFeature : object, Xunit.IClassFixture<DisbandAllExpiredCrewsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "DisbandExpiredCrews.feature"
#line hidden
        
        public DisbandAllExpiredCrewsFeature(DisbandAllExpiredCrewsFeature.FixtureData fixtureData, BKA_Tools_CrewFinding_BehaviourTest_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Crews/Features/Commands", "Disband All Expired Crews", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
    #line hidden
#line 4
        testRunner.Given("the system is configured to get the crews created in the last \"4\" hours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Disband all expired crews")]
        [Xunit.TraitAttribute("FeatureTitle", "Disband All Expired Crews")]
        [Xunit.TraitAttribute("Description", "Disband all expired crews")]
        public void DisbandAllExpiredCrews()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Disband all expired crews", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "CrewId",
                            "CaptainHandle",
                            "CreatedAgoHours",
                            "MaxCrewSize",
                            "System",
                            "PlanetarySystem",
                            "PlanetMoon",
                            "Location",
                            "Description",
                            "Activity",
                            "CurrentCrewSize",
                            "IsExpired"});
                table3.AddRow(new string[] {
                            "1",
                            "Rowan",
                            "1",
                            "4",
                            "Stanton",
                            "Crusader",
                            "Crusader",
                            "Seraphim Station",
                            "Elite bounty hunters",
                            "Bounty Hunting",
                            "4",
                            "true"});
                table3.AddRow(new string[] {
                            "2",
                            "Ada",
                            "3",
                            "5",
                            "Terra",
                            "Sol",
                            "Terra",
                            "New Austin",
                            "Space explorers",
                            "Exploration",
                            "3",
                            "false"});
                table3.AddRow(new string[] {
                            "3",
                            "Kai",
                            "5",
                            "3",
                            "Hurston",
                            "Stanton",
                            "Ariel",
                            "Lorville",
                            "Lunar miners",
                            "Mining",
                            "2",
                            "true"});
#line 7
        testRunner.Given("there is the following crews in the system", ((string)(null)), table3, "Given ");
#line hidden
#line 12
        testRunner.When("the system disbands all expired crews", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "CrewId"});
                table4.AddRow(new string[] {
                            "1"});
                table4.AddRow(new string[] {
                            "3"});
#line 13
        testRunner.Then("the following crewsId should be removed", ((string)(null)), table4, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                DisbandAllExpiredCrewsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                DisbandAllExpiredCrewsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
