name: Main Pipepline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: 'bka-crewfinding'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/BKA.Tools.CrewFinding.API.Functions'
  DOTNET_VERSION: '8.0.x'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Restore Dependencies'
        run: dotnet restore ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: 'Build Project'
        run: |
          mkdir -p ./output
          dotnet build ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release --output ./output

      - name: 'Save Build Output'
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./output

      - name: 'Build and Test Behaviour Tests'
        run: |
          dotnet build src/BKA.Tools.CrewFinding.BehaviourTest --configuration Release
          dotnet test src/BKA.Tools.CrewFinding.BehaviourTest --configuration Release --no-build --verbosity normal

      - name: 'Build and Test Unit Tests'
        run: |
          dotnet build src/BKA.Tools.CrewFinding.Tests --configuration Release
          dotnet test src/BKA.Tools.CrewFinding.Tests --configuration Release --no-build --verbosity normal

      - name: 'Build and Test DataAccess Tests'
        run: |
          dotnet build src/BKA.Tools.CrewFinding.DataAccess.CosmosDb.Tests --configuration Release
          dotnet test src/BKA.Tools.CrewFinding.DataAccess.CosmosDb.Tests --configuration Release --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Download Build Output'
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'bkacrewfinding'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E0E5CF707023480C9BF43E447BDB6A43 }}
